title: Knowing Institute
baseurl: /
permalink: '/:title/'
collections:
  posts:
    permalink: '/posts/:title/'
header:
  title: Knowing Institute
  has_nav: true
  nav_links:
    - label: Home
      url: /
    - label: The Protocol
      url: /protocol/
    - label: Contact
      url: /contact/
footer:
  content: '&copy; 2021 Knowing Institute. All rights reserved.'
  has_social: false
  social_links:
    - label: Twitter
      url: 'https://twitter.com/'
      new_window: true
    - label: Instagram
      url: 'https://www.instagram.com/'
      new_window: true
    - label: GitHub
      url: 'https://github.com/'
      new_window: true
    - label: LinkedIn
      url: 'https://www.linkedin.com/'
      new_window: true
    - label: DEV
      url: 'https://dev.to/'
      new_window: true
sass:
  indentWidth: 4
  style: nested
  precision: 10
plugins:
  - jekyll-menus
exclude:
  - Gemfile
  - Gemfile.lock
  - node_modules
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/
  - LICENSE.md
  - README.md
  - netlify.toml
  - stackbit-build.sh
  - stackbit-pull.js
domain: 'https://knowinginstitute.org'
